package com.mycompany.model.entity;

import com.mycompany.model.entity.enums.PurchaseOrderStatus;
import jakarta.persistence.*;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Entity representing a Purchase Order (Orden de Compra) in the pharmacy management system.
 * Maps to the 'purchase_orders' table in the database.
 *
 * A purchase order is created by an administrator to request products from a supplier.
 * It goes through several states: DRAFT → SENT → CONFIRMED → IN_TRANSIT → RECEIVING → RECEIVED
 *
 * @author ramir
 */
@Entity
@Table(name = "purchase_orders")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PurchaseOrder implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "order_id")
    private Integer orderId;

    /**
     * Order number - unique identifier for the order.
     * Format: OC-{branchId}-{year}-{sequence}
     * Example: OC-1-2025-000001
     * Can be null initially (generated by database function or service)
     */
    @Column(name = "order_number", unique = true, length = 50)
    @Size(max = 50)
    private String orderNumber;

    /**
     * Supplier who will fulfill this order.
     * Required field - cannot create order without supplier.
     */
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "supplier_id", nullable = false)
    @NotNull(message = "Debe seleccionar un proveedor")
    private Supplier supplier;

    /**
     * Branch/location that is ordering the products.
     * Required field.
     */
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "branch_id", nullable = false)
    @NotNull(message = "Debe seleccionar una sucursal")
    private Branch branch;

    /**
     * Date when the order was created.
     * Auto-set to current timestamp on creation.
     */
    @Column(name = "order_date")
    @Temporal(TemporalType.TIMESTAMP)
    private Date orderDate;

    /**
     * Current status of the order.
     * Default: DRAFT
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", length = 20)
    @Builder.Default
    private PurchaseOrderStatus status = PurchaseOrderStatus.DRAFT;

    /**
     * Date when order was sent to supplier.
     * Set when status changes to SENT.
     */
    @Column(name = "sent_date")
    @Temporal(TemporalType.TIMESTAMP)
    private Date sentDate;

    /**
     * Date when supplier confirmed the order.
     * Set when status changes to CONFIRMED.
     */
    @Column(name = "confirmed_date")
    @Temporal(TemporalType.TIMESTAMP)
    private Date confirmedDate;

    /**
     * Supplier's confirmation number or reference.
     * Optional - some suppliers provide their own order number.
     */
    @Column(name = "supplier_confirmation_number", length = 50)
    @Size(max = 50)
    private String supplierConfirmationNumber;

    /**
     * Date when receiving process started.
     * Set when status changes to RECEIVING.
     */
    @Column(name = "receiving_started_at")
    @Temporal(TemporalType.TIMESTAMP)
    private Date receivingStartedAt;

    /**
     * Date when all products were received.
     * Set when status changes to RECEIVED.
     */
    @Column(name = "received_date")
    @Temporal(TemporalType.TIMESTAMP)
    private Date receivedDate;

    /**
     * Subtotal amount (sum of all detail line totals).
     * Calculated from order details.
     */
    @Column(name = "subtotal", precision = 12, scale = 2)
    @DecimalMin(value = "0.00", message = "El subtotal debe ser mayor o igual a 0")
    private BigDecimal subtotal;

    /**
     * Tax amount (IVA 12% in Guatemala).
     * Calculated as subtotal * 0.12
     */
    @Column(name = "tax_amount", precision = 12, scale = 2)
    @Builder.Default
    private BigDecimal taxAmount = BigDecimal.ZERO;

    /**
     * Shipping/delivery cost.
     * Optional - can be 0.
     */
    @Column(name = "shipping_cost", precision = 10, scale = 2)
    @Builder.Default
    private BigDecimal shippingCost = BigDecimal.ZERO;

    /**
     * Total amount including taxes and shipping.
     * total = subtotal + taxAmount + shippingCost
     */
    @Column(name = "total_amount", precision = 12, scale = 2)
    private BigDecimal totalAmount;

    /**
     * Reason for cancellation (if order is cancelled).
     * Required when status is CANCELLED.
     */
    @Column(name = "cancellation_reason", columnDefinition = "TEXT")
    private String cancellationReason;

    /**
     * User ID who cancelled the order.
     * Set when order is cancelled.
     */
    @Column(name = "cancelled_by", length = 50)
    @Size(max = 50)
    private String cancelledBy;

    /**
     * Date when order was cancelled.
     * Set when status changes to CANCELLED.
     */
    @Column(name = "cancellation_date")
    @Temporal(TemporalType.TIMESTAMP)
    private Date cancellationDate;

    /**
     * General notes or observations about the order.
     * Free text field for any additional information.
     */
    @Column(name = "notes", columnDefinition = "TEXT")
    private String notes;

    /**
     * Timestamp when order was created.
     * Auto-set on insert.
     */
    @Column(name = "created_at")
    @Temporal(TemporalType.TIMESTAMP)
    private Date createdAt;

    /**
     * Timestamp when order was last updated.
     * Auto-updated on every change.
     */
    @Column(name = "updated_at")
    @Temporal(TemporalType.TIMESTAMP)
    private Date updatedAt;

    /**
     * User ID who created the order.
     * Typically an ADMIN user.
     */
    @Column(name = "created_by", length = 50)
    @Size(max = 50)
    private String createdBy;

    /**
     * Order details - list of products being ordered.
     * Cascade all operations to details.
     * Orphan removal: if detail is removed from list, delete from DB.
     */
    @OneToMany(mappedBy = "purchaseOrder", cascade = CascadeType.ALL,
               fetch = FetchType.LAZY, orphanRemoval = true)
    @Builder.Default
    private List<PurchaseOrderDetail> orderDetails = new ArrayList<>();

    /**
     * Lifecycle callback - executed before persisting new entity.
     * Sets creation and update timestamps.
     */
    @PrePersist
    protected void onCreate() {
        createdAt = new Date();
        updatedAt = new Date();
        if (orderDate == null) {
            orderDate = new Date();
        }
        if (status == null) {
            status = PurchaseOrderStatus.DRAFT;
        }
    }

    /**
     * Lifecycle callback - executed before updating entity.
     * Updates the updatedAt timestamp.
     */
    @PreUpdate
    protected void onUpdate() {
        updatedAt = new Date();
    }

    /**
     * Helper method to add a detail to this order.
     * Maintains bidirectional relationship.
     *
     * @param detail the purchase order detail to add
     */
    public void addDetail(PurchaseOrderDetail detail) {
        if (orderDetails == null) {
            orderDetails = new ArrayList<>();
        }
        orderDetails.add(detail);
        detail.setPurchaseOrder(this);
    }

    /**
     * Helper method to remove a detail from this order.
     * Maintains bidirectional relationship.
     *
     * @param detail the purchase order detail to remove
     */
    public void removeDetail(PurchaseOrderDetail detail) {
        if (orderDetails != null) {
            orderDetails.remove(detail);
            detail.setPurchaseOrder(null);
        }
    }

    /**
     * Calculate totals based on order details.
     * Should be called after modifying details.
     */
    public void calculateTotals() {
        if (orderDetails == null || orderDetails.isEmpty()) {
            subtotal = BigDecimal.ZERO;
            taxAmount = BigDecimal.ZERO;
            totalAmount = BigDecimal.ZERO;
            return;
        }

        // Sum all detail subtotals
        subtotal = orderDetails.stream()
                .map(PurchaseOrderDetail::getSubtotal)
                .filter(s -> s != null)
                .reduce(BigDecimal.ZERO, BigDecimal::add);

        // Calculate tax (12% IVA)
        taxAmount = subtotal.multiply(new BigDecimal("0.12"));

        // Calculate total
        totalAmount = subtotal.add(taxAmount);
        if (shippingCost != null) {
            totalAmount = totalAmount.add(shippingCost);
        }
    }
}
