package com.mycompany.model.entity;

import com.mycompany.model.entity.enums.PurchaseReceiptStatus;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Entity representing a Purchase Receipt (Recepción de Compra) in the pharmacy management system.
 * Maps to the 'purchase_receipts' table in the database.
 *
 * A purchase receipt is created when a storekeeper receives products from a purchase order.
 * It tracks what was actually received, including damaged items.
 *
 * @author ramir
 */
@Entity
@Table(name = "purchase_receipts")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PurchaseReceipt implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "receipt_id")
    private Integer receiptId;

    /**
     * Purchase order being received.
     * Required - receipt must be associated with an order.
     */
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "order_id", nullable = false)
    @NotNull(message = "La orden de compra es requerida")
    private PurchaseOrder purchaseOrder;

    /**
     * Receipt number - unique identifier for the receipt.
     * Format: REC-{year}-{sequence} or REC-{year}-{sequence}-P{partial_number}
     * Example: REC-2025-000001 or REC-2025-000001-P2
     * Generated by database function.
     */
    @Column(name = "receipt_number", unique = true, nullable = false, length = 50)
    @NotBlank(message = "El número de recepción es requerido")
    @Size(max = 50)
    private String receiptNumber;

    /**
     * Date and time when products were received.
     * Auto-set to current timestamp on creation.
     */
    @Column(name = "receipt_date")
    @Temporal(TemporalType.TIMESTAMP)
    private Date receiptDate;

    /**
     * User ID who received the products (storekeeper).
     * Required field.
     */
    @Column(name = "received_by", nullable = false, length = 50)
    @NotBlank(message = "El usuario que recibe es requerido")
    @Size(max = 50)
    private String receivedBy;

    /**
     * Branch/location where products were received.
     * Required field.
     */
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "branch_id", nullable = false)
    @NotNull(message = "La sucursal es requerida")
    private Branch branch;

    /**
     * Supplier's invoice number.
     * Optional - links this receipt to supplier's paperwork.
     */
    @Column(name = "supplier_invoice_number", length = 50)
    @Size(max = 50)
    private String supplierInvoiceNumber;

    /**
     * Date on supplier's invoice.
     * Optional.
     */
    @Column(name = "supplier_invoice_date")
    private LocalDate supplierInvoiceDate;

    /**
     * Indicates if this is a partial receipt.
     * True if not all ordered products were received yet.
     */
    @Column(name = "is_partial")
    @Builder.Default
    private Boolean isPartial = false;

    /**
     * Indicates if this is the final receipt for the order.
     * True if no more products are expected.
     */
    @Column(name = "is_final")
    @Builder.Default
    private Boolean isFinal = false;

    /**
     * Current status of the receipt.
     * Default: DRAFT
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", length = 20)
    @Builder.Default
    private PurchaseReceiptStatus status = PurchaseReceiptStatus.DRAFT;

    /**
     * Date when receipt was completed and processed.
     * Set when status changes to COMPLETE.
     */
    @Column(name = "completed_date")
    @Temporal(TemporalType.TIMESTAMP)
    private Date completedDate;

    /**
     * User ID who completed the receipt.
     * Set when receipt is finalized.
     */
    @Column(name = "completed_by", length = 50)
    @Size(max = 50)
    private String completedBy;

    /**
     * General notes or observations about the receipt.
     * Can include information about damaged items, delivery issues, etc.
     */
    @Column(name = "notes", columnDefinition = "TEXT")
    private String notes;

    /**
     * Timestamp when receipt was created.
     * Auto-set on insert.
     */
    @Column(name = "created_at")
    @Temporal(TemporalType.TIMESTAMP)
    private Date createdAt;

    /**
     * Timestamp when receipt was last updated.
     * Auto-updated on every change.
     */
    @Column(name = "updated_at")
    @Temporal(TemporalType.TIMESTAMP)
    private Date updatedAt;

    /**
     * Receipt details - list of products received.
     * Cascade all operations to details.
     * Orphan removal: if detail is removed from list, delete from DB.
     */
    @OneToMany(mappedBy = "purchaseReceipt", cascade = CascadeType.ALL,
               fetch = FetchType.LAZY, orphanRemoval = true)
    @Builder.Default
    private List<PurchaseReceiptDetail> receiptDetails = new ArrayList<>();

    /**
     * Lifecycle callback - executed before persisting new entity.
     * Sets creation and update timestamps.
     */
    @PrePersist
    protected void onCreate() {
        createdAt = new Date();
        updatedAt = new Date();
        if (receiptDate == null) {
            receiptDate = new Date();
        }
        if (status == null) {
            status = PurchaseReceiptStatus.DRAFT;
        }
    }

    /**
     * Lifecycle callback - executed before updating entity.
     * Updates the updatedAt timestamp.
     */
    @PreUpdate
    protected void onUpdate() {
        updatedAt = new Date();
    }

    /**
     * Helper method to add a detail to this receipt.
     * Maintains bidirectional relationship.
     *
     * @param detail the purchase receipt detail to add
     */
    public void addDetail(PurchaseReceiptDetail detail) {
        if (receiptDetails == null) {
            receiptDetails = new ArrayList<>();
        }
        receiptDetails.add(detail);
        detail.setPurchaseReceipt(this);
    }

    /**
     * Helper method to remove a detail from this receipt.
     * Maintains bidirectional relationship.
     *
     * @param detail the purchase receipt detail to remove
     */
    public void removeDetail(PurchaseReceiptDetail detail) {
        if (receiptDetails != null) {
            receiptDetails.remove(detail);
            detail.setPurchaseReceipt(null);
        }
    }

    /**
     * Calculate total quantity received across all details.
     *
     * @return total quantity received
     */
    public Integer getTotalQuantityReceived() {
        if (receiptDetails == null || receiptDetails.isEmpty()) {
            return 0;
        }
        return receiptDetails.stream()
                .map(PurchaseReceiptDetail::getQuantityReceived)
                .filter(q -> q != null)
                .reduce(0, Integer::sum);
    }

    /**
     * Calculate total quantity damaged across all details.
     *
     * @return total quantity damaged
     */
    public Integer getTotalQuantityDamaged() {
        if (receiptDetails == null || receiptDetails.isEmpty()) {
            return 0;
        }
        return receiptDetails.stream()
                .map(PurchaseReceiptDetail::getQuantityDamaged)
                .filter(q -> q != null)
                .reduce(0, Integer::sum);
    }

    /**
     * Calculate total quantity available (received - damaged).
     *
     * @return total quantity available for sale
     */
    public Integer getTotalQuantityAvailable() {
        return getTotalQuantityReceived() - getTotalQuantityDamaged();
    }
}
